services:
    crafty:
        container_name: crafty_container
        image: registry.gitlab.com/crafty-controller/crafty-4:latest
        restart: always
        environment:
            - TZ=Etc/UTC
        ports:
            - "8443:8443" # HTTPS
            - "8123:8123" # DYNMAP
            - "19132:19132/udp" # BEDROCK
            - "25500-25600:25500-25600" # MC SERV PORT RANGE
        volumes:
            - /data/chyld/minecraft/backups:/crafty/backups:Z
            - /data/chyld/minecraft/logs:/crafty/logs:Z
            - /data/chyld/minecraft/servers:/crafty/servers:Z
            - /data/chyld/minecraft/config:/crafty/app/config:Z
            - /data/chyld/minecraft/import:/crafty/import:Z
