services:
    crafty:
        container_name: crafty_container
        image: registry.gitlab.com/crafty-controller/crafty-4:latest
        restart: always
        environment:
            - TZ=Etc/UTC
        ports:
            - "8443:8443" # HTTPS
            - "8123:8123" # DYNMAP
            - "19132:19132/udp" # BEDROCK
            - "25500-25600:25500-25600" # MC SERV PORT RANGE
        volumes:
            - ./minecraft/backups:/crafty/backups
            - ./minecraft/logs:/crafty/logs
            - ./minecraft/servers:/crafty/servers
            - ./minecraft/config:/crafty/app/config
            - ./minecraft/import:/crafty/import

