[accounts]
  u1: p1
  u2: p2
  u3: p3
[/Books]
  /mnt/Books
  accs:
    r: *                 # read-only, everybody
[/Files]
  /mnt/Files
  accs:
    r: *                 # read-only, everybody
[/Media]
  /mnt/Media
  accs:
    r: *                 # read-only, everybody
[/Photos]
  /mnt/Photos
  accs:
    r: *                 # read-only, everybody
[/Bucket]
  /mnt/Bucket
  accs:
    rw: u3               # u3 can read/write

